### ISSUE TITLE
Check if role supports official nginx role

### ISSUE THREAD

**Issue by rndmh3ro** [dev-sec/ansible-nginx-hardening#15]
Nginx now provides an offical ansible role: https://www.nginx.com/blog/official-ansible-galaxy-nginx-roles-out-now/

We should make sure that our hardening-role works with the official nginx-role!

**Comment by szEvEz** [comment]
I tested the hardening role with the [official nginx-role](https://github.com/nginxinc/ansible-role-nginx) on centos/7 with the following playbook

```
---
- hosts: localhost
  become: true
  roles:
    - nginxinc.nginx
    - dev-sec.nginx-hardening
```

I ran the inspec nginx baseline against it with the following result:
`Test Summary: 32 successful, 0 failures, 2 skipped`

What next steps would you suggest?
